kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "tribal-wars-bot-agent-data"
  labels:
    app: "tribal-wars-bot-agent"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
